const CATEGORIES = [
  { id: 'food',               label: 'Food',                icon: '🍽️' },
  { id: 'housing',            label: 'Housing',             icon: '🏠' },
  { id: 'healthcare',         label: 'Healthcare',          icon: '⚕️' },
  { id: 'mental-health',      label: 'Mental Health',       icon: '🧠' },
  { id: 'substance-recovery', label: 'Substance Recovery',  icon: '💊' },
  { id: 'employment',         label: 'Employment',          icon: '💼' },
  { id: 'transportation',     label: 'Transportation',      icon: '🚌' },
  { id: 'childcare',          label: 'Childcare',           icon: '👶' },
  { id: 'legal-aid',          label: 'Legal Aid',           icon: '⚖️' },
  { id: 'utilities',          label: 'Utilities Assistance',icon: '💡' },
  { id: 'clothing',           label: 'Clothing & Household',icon: '👕' },
];

const RESOURCES = [
  // ── FOOD ──────────────────────────────────────────────────────────────────
  {
    id: 'spartanburg-area-food-bank',
    name: 'Spartanburg Area Food Bank',
    category: 'food',
    address: '355 Dupre Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 582-3576',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Open to Spartanburg County residents in need. No income verification required for most programs.',
    description: 'Distributes food through 100+ partner agencies across Spartanburg County. Provides emergency food boxes and connects families with local pantry partners closest to them.',
    website: 'https://www.spartanburgfoodbank.org',
    mapsUrl: 'https://maps.google.com/?q=355+Dupre+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'soup-kitchen-spartanburg',
    name: 'Spartanburg Soup Kitchen',
    category: 'food',
    address: '136 S Forest St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 585-0022',
    hours: 'Every day 7:30 AM – 2:00 PM',
    eligibility: 'Anyone in need is welcome. No ID or documentation required.',
    description: 'Serves free hot meals every day to anyone who shows up hungry. Also provides food boxes and connects guests with other social services in Spartanburg.',
    website: 'https://spartanburgsoupkitchen.org',
    mapsUrl: 'https://maps.google.com/?q=136+S+Forest+St+Spartanburg+SC+29306',
  },
  {
    id: 'mobile-meals-spartanburg',
    name: 'Mobile Meals of Spartanburg',
    category: 'food',
    address: 'Delivers to Spartanburg County',
    zip: '29301',
    phone: '(864) 573-0015',
    hours: 'Mon–Fri delivery (call to enroll)',
    eligibility: 'Homebound seniors and adults with disabilities who cannot prepare meals independently.',
    description: 'Delivers hot, nutritious meals to homebound seniors and disabled adults throughout Spartanburg County. Volunteer drivers also provide friendly check-ins.',
    website: null,
    mapsUrl: null,
  },

  {
    id: 'regenesis-health-care',
    name: 'ReGenesis Health Care',
    category: 'healthcare',
    address: '301 Crescent Ave, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-2411',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM (multiple locations — call for specific hours)',
    eligibility: 'Open to all. Accepts all insurance including Medicaid and Medicare. Sliding fee scale for uninsured patients based on income.',
    description: 'Federally Qualified Health Center with multiple Spartanburg locations offering primary care, dental, behavioral health, and pharmacy services. No one turned away for inability to pay. Also has locations on N Pine St (dental), S Church St, and Langdon St.',
    website: 'https://www.myrhc.org',
    mapsUrl: 'https://maps.google.com/?q=301+Crescent+Ave+Spartanburg+SC+29306',
  },
  {
    id: 'st-lukes-free-medical-clinic',
    name: "St. Luke's Free Medical Clinic",
    category: 'healthcare',
    address: '162 N Dean St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 542-2273',
    hours: 'By appointment only — call to schedule. New patient applications: Mon 10am–1pm & Thu 1–4pm.',
    eligibility: 'Uninsured adults who cannot afford care. Appointment required — walk-ins not accepted.',
    description: 'Volunteer-run free medical clinic providing primary care, chronic disease management, and prescription assistance to uninsured adults. Call to confirm current clinic schedule before visiting. Satellite clinic at 101 St Matthews Ln (call for hours).',
    website: 'https://www.slfmc.org',
    mapsUrl: 'https://maps.google.com/?q=162+N+Dean+St+Spartanburg+SC+29302',
  },

  // ── HOUSING ───────────────────────────────────────────────────────────────
  {
    id: 'union-mission-spartanburg',
    name: 'Union Mission of Spartanburg',
    category: 'housing',
    address: '144 Union St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 582-7553',
    hours: 'Open 24/7 for emergency intake',
    eligibility: 'Adult men needing emergency shelter. Women and family shelter available — call for current space.',
    description: 'Emergency shelter, transitional housing, daily meals, and recovery programs for homeless individuals. Operates separate men\'s and women\'s facilities with wraparound support services.',
    website: 'https://www.unionmission.org',
    mapsUrl: 'https://maps.google.com/?q=144+Union+St+Spartanburg+SC+29302',
  },
  {
    id: 'spartanburg-housing-authority',
    name: 'Spartanburg Housing Authority',
    category: 'housing',
    address: '170 Arch St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 598-6000',
    hours: 'Mon–Thu 8:30 AM – 5:30 PM · Fri 8:30 AM – Noon',
    eligibility: 'Low-income families, elderly, and disabled individuals. Income limits apply. Waiting lists may be in effect — call to check status.',
    description: 'Manages public housing units and administers Housing Choice Vouchers (Section 8) to help low-income residents afford safe housing in Spartanburg.',
    website: 'https://www.spartanburghousing.org',
    mapsUrl: 'https://maps.google.com/?q=170+Arch+St+Spartanburg+SC+29303',
  },
  {
    id: 'safe-homes-spartanburg',
    name: 'SAFE Homes – Rape Crisis Coalition',
    category: 'housing',
    address: 'Confidential location, Spartanburg, SC',
    zip: '29301',
    phone: '1-800-273-5066',
    hours: '24/7 Crisis Hotline · Office Mon–Fri 8:30 AM – 5:00 PM: (864) 583-9803',
    eligibility: 'Survivors of domestic violence, sexual assault, and stalking. Services are free and confidential.',
    description: 'Provides emergency shelter (up to 60 days) for women and children, crisis counseling, legal advocacy, and safety planning. 24/7 hotline: 1-800-273-5066. Office: (864) 583-9803. Your location is never shared.',
    website: 'https://www.safehomessc.org',
    mapsUrl: null,
  },
  {
    id: 'bethlehem-center',
    name: 'Bethlehem Center',
    category: 'housing',
    address: '1066 W Main St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 585-0886',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income families and individuals in Spartanburg County. Documentation required — call ahead.',
    description: 'Community center providing emergency rental and utility assistance, food, clothing, and case management to stabilize families in crisis and prevent homelessness.',
    website: 'https://www.bethlehemcenter.org',
    mapsUrl: 'https://maps.google.com/?q=1066+W+Main+St+Spartanburg+SC+29301',
  },

  // ── HEALTHCARE ────────────────────────────────────────────────────────────
  {
    id: 'spartanburg-community-health-centers',
    name: 'Spartanburg Community Health Centers',
    category: 'healthcare',
    address: '484 Southport Rd, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-1751',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Open to all. Sliding fee scale based on income. Medicaid, Medicare, and uninsured patients all welcome.',
    description: 'Federally Qualified Health Center (FQHC) offering primary care, dental, behavioral health, and pharmacy services. No one is turned away for inability to pay.',
    website: 'https://www.schealthlink.com',
    mapsUrl: 'https://maps.google.com/?q=484+Southport+Rd+Spartanburg+SC+29306',
  },
  {
    id: 'free-medical-clinic-upstate',
    name: 'Free Medical Clinic of the Upstate',
    category: 'healthcare',
    address: '174 S Forest St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 576-6566',
    hours: 'Tue & Thu evenings — call for current schedule',
    eligibility: 'Uninsured adults who meet income guidelines and live or work in Spartanburg County.',
    description: 'Volunteer-run clinic providing free primary care, lab work, and prescription medications to uninsured working adults who do not qualify for Medicaid.',
    website: 'https://www.fmcupstate.org',
    mapsUrl: 'https://maps.google.com/?q=174+S+Forest+St+Spartanburg+SC+29306',
  },
  {
    id: 'spartanburg-regional-medical-center',
    name: 'Spartanburg Regional Medical Center',
    category: 'healthcare',
    address: '101 E Wood St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 560-6000',
    hours: 'Emergency Room open 24/7',
    eligibility: 'Emergency care available to all regardless of insurance or ability to pay. Financial assistance programs available.',
    description: 'Full-service regional hospital with 24/7 emergency care. Charity care and financial assistance programs are available — ask the billing department or a patient advocate.',
    website: 'https://www.spartanburgregional.com',
    mapsUrl: 'https://maps.google.com/?q=101+E+Wood+St+Spartanburg+SC+29303',
  },

  // ── MENTAL HEALTH ─────────────────────────────────────────────────────────
  {
    id: 'spartanburg-community-mental-health',
    name: 'Spartanburg Area Mental Health Center',
    category: 'mental-health',
    address: '250 Dewey Ave, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 585-0366',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM · 24/7 Crisis Line: (800) 277-1366',
    eligibility: 'Open to all Spartanburg County residents. Sliding fee scale. Medicaid accepted. No one turned away.',
    description: 'State-funded center offering outpatient therapy, psychiatric services, crisis intervention, and case management. Specializes in serving people with limited income or no insurance. 24/7 crisis line: (800) 277-1366.',
    website: 'https://sparmhc.org',
    mapsUrl: 'https://maps.google.com/?q=250+Dewey+Ave+Spartanburg+SC+29303',
  },
  {
    id: '988-crisis-lifeline',
    name: '988 Suicide & Crisis Lifeline',
    category: 'mental-health',
    address: null,
    zip: null,
    phone: '988',
    hours: '24/7 — call or text anytime',
    eligibility: 'Anyone in emotional distress or suicidal crisis. Free and confidential.',
    description: 'Call or text 988 to reach a trained crisis counselor. Available 24 hours a day, every day. Chat also available at 988lifeline.org. Deaf/hard of hearing: use your relay service.',
    website: 'https://988lifeline.org',
    mapsUrl: null,
  },
  {
    id: 'crisis-text-line',
    name: 'Crisis Text Line',
    category: 'mental-health',
    address: null,
    zip: null,
    phone: 'Text HOME to 741741',
    hours: '24/7',
    eligibility: 'Anyone in crisis. Free, confidential, and text-based.',
    description: 'Text HOME to 741741 to connect with a trained crisis counselor via text message. Good option if you cannot make a phone call or prefer to text.',
    website: 'https://www.crisistextline.org',
    mapsUrl: null,
  },

  {
    id: 'shepherds-center-spartanburg',
    name: "Shepherd's Center of Spartanburg",
    category: 'healthcare',
    address: '393 E Main St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 585-1999',
    hours: 'Mon–Fri — call for current class and program schedule',
    eligibility: 'Active seniors in Spartanburg. Most programs are free or low-cost.',
    description: 'Provides seniors with programs for physical fitness (line dancing, aerobics, tai chi), lifelong learning classes, mental wellness activities, and volunteer opportunities. Focused on helping older adults stay active, connected, and independent.',
    website: 'https://spartanburgshepherdcenter.org',
    mapsUrl: 'https://maps.google.com/?q=393+E+Main+St+Spartanburg+SC+29302',
  },

  // ── SUBSTANCE RECOVERY ────────────────────────────────────────────────────
  {
    id: 'beckman-center',
    name: 'Beckman Center for Mental Health Services',
    category: 'substance-recovery',
    address: '1 Beckman Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 582-7588',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Adults with substance use disorders. Medicaid, Medicare, and self-pay on sliding scale.',
    description: 'Outpatient substance use treatment including individual and group counseling, medication-assisted treatment (MAT), and recovery support services.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=1+Beckman+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'samhsa-helpline',
    name: 'SAMHSA National Helpline',
    category: 'substance-recovery',
    address: null,
    zip: null,
    phone: '1-800-662-4357',
    hours: '24/7, 365 days a year',
    eligibility: 'Anyone struggling with substance use or mental health. Free, confidential, English and Spanish.',
    description: 'Dial 1-800-662-HELP for free, confidential referrals to local treatment facilities, support groups, and community-based organizations. Available in English and Spanish.',
    website: 'https://www.samhsa.gov/find-help/national-helpline',
    mapsUrl: null,
  },
  {
    id: 'aa-spartanburg',
    name: 'Alcoholics Anonymous – Spartanburg',
    category: 'substance-recovery',
    address: 'Multiple meeting locations in Spartanburg',
    zip: '29301',
    phone: '(864) 582-9573',
    hours: 'Meetings 7 days a week — see website for schedule',
    eligibility: 'Anyone with a desire to stop drinking. No fees, no requirements.',
    description: 'AA offers free peer support meetings throughout Spartanburg. Call the local intergroup number or visit the website to find a meeting near you — any day of the week.',
    website: 'https://www.aaspartanburg.org',
    mapsUrl: null,
  },

  // ── EMPLOYMENT ────────────────────────────────────────────────────────────
  {
    id: 'sc-works-spartanburg',
    name: 'SC Works Spartanburg',
    category: 'employment',
    address: '145 N Church St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 764-1966',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'All job seekers. Services are free.',
    description: 'State workforce center with job listings, resume assistance, skills training funding, unemployment support, and access to computers and internet. Drop-ins welcome.',
    website: 'https://scworksupstate.com',
    mapsUrl: 'https://maps.google.com/?q=145+N+Church+St+Spartanburg+SC+29306',
  },
  {
    id: 'goodwill-job-training',
    name: 'Goodwill – Job Training & Placement',
    category: 'employment',
    address: '424 W Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 583-3000',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Anyone facing barriers to employment. Free programs.',
    description: 'Free job skills training, digital literacy classes, and employment placement services. Especially focused on individuals with disabilities, gaps in work history, or past criminal records.',
    website: 'https://www.goodwillsc.org',
    mapsUrl: 'https://maps.google.com/?q=424+W+Main+St+Spartanburg+SC+29306',
  },

  // ── TRANSPORTATION ────────────────────────────────────────────────────────
  {
    id: 'sparta-transit',
    name: 'SPARTA – Spartanburg Area Transit',
    category: 'transportation',
    address: '170 S Henry St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 327-2222',
    hours: 'Mon–Sat 6:00 AM – 7:00 PM (route dependent)',
    eligibility: 'Open to all. Reduced fares for seniors (65+) and riders with disabilities. Paratransit available for eligible riders.',
    description: 'Public bus system with fixed routes through Spartanburg city and county. Paratransit (door-to-door) service available for qualified riders who cannot use fixed-route buses.',
    website: 'https://www.ridesparta.com',
    mapsUrl: 'https://maps.google.com/?q=170+S+Henry+St+Spartanburg+SC+29306',
  },

  // ── CHILDCARE ─────────────────────────────────────────────────────────────
  {
    id: 'dss-spartanburg',
    name: 'Spartanburg DSS – Benefits & Child Services',
    category: 'childcare',
    address: '200 Magnolia St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 596-2770',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income families with children. Income guidelines apply for childcare subsidies.',
    description: 'Department of Social Services office handling childcare subsidy vouchers, SNAP food assistance, Medicaid enrollment, TANF cash assistance, and child protective services.',
    website: 'https://dss.sc.gov',
    mapsUrl: 'https://maps.google.com/?q=200+Magnolia+St+Spartanburg+SC+29306',
  },
  {
    id: 'child-abuse-prevention-association',
    name: 'CAPA – Child Abuse Prevention Association',
    category: 'childcare',
    address: '167 W Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-3252',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Families with children in Spartanburg County. Income-based programs available.',
    description: 'Parenting education, family support services, home visiting programs, and crisis assistance designed to prevent child abuse and help families stay safely together.',
    website: 'https://www.capasc.org',
    mapsUrl: 'https://maps.google.com/?q=167+W+Main+St+Spartanburg+SC+29306',
  },

  // ── LEGAL AID ─────────────────────────────────────────────────────────────
  {
    id: 'palmetto-legal-aid',
    name: 'SC Legal Services – Spartanburg',
    category: 'legal-aid',
    address: '148 E Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(888) 346-5592',
    hours: 'Mon–Wed & Fri 8:30 AM – 5:00 PM · Thu 8:30 AM – 7:00 PM',
    eligibility: 'Households at or below 125% of federal poverty level in Spartanburg County.',
    description: 'Free civil legal representation for low-income residents. Handles evictions, foreclosure prevention, domestic violence protection orders, public benefits denials, and family law matters.',
    website: 'https://sclegal.org',
    mapsUrl: 'https://maps.google.com/?q=148+E+Main+St+Spartanburg+SC+29306',
  },
  {
    id: 'sc-bar-pro-bono',
    name: 'SC Bar Pro Bono Program',
    category: 'legal-aid',
    address: 'Statewide — call for Spartanburg referrals',
    zip: '29301',
    phone: '1-800-868-2284',
    hours: 'Mon–Fri 9:00 AM – 5:00 PM',
    eligibility: 'Low-income individuals who need civil legal help and do not qualify for SC Legal Services.',
    description: 'Connects low-income South Carolinians with volunteer attorneys for free legal advice and representation. Call the statewide hotline and ask for Spartanburg referrals.',
    website: 'https://www.scbar.org/public/get-legal-help/pro-bono-program/',
    mapsUrl: null,
  },

  // ── UTILITIES ASSISTANCE ──────────────────────────────────────────────────
  {
    id: 'salvation-army-spartanburg',
    name: 'Salvation Army of Spartanburg',
    category: 'utilities',
    address: '1529 John B White Sr Blvd, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 576-6670',
    hours: 'Mon–Fri 9:00 AM – 5:00 PM',
    eligibility: 'Spartanburg County residents in financial crisis. Income verification and ID required.',
    description: 'Emergency utility assistance (electric, gas, water), rent assistance, and food boxes for residents in crisis. Limited funds available — call early in the month for best availability.',
    website: 'https://centralsc.salvationarmy.org/spartanburg',
    mapsUrl: 'https://maps.google.com/?q=1529+John+B+White+Sr+Blvd+Spartanburg+SC+29301',
  },
  {
    id: 'sc-liheap',
    name: 'SC LIHEAP – Energy Bill Assistance',
    category: 'utilities',
    address: 'Apply at DSS: 200 Magnolia St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(800) 311-7220',
    hours: 'Applications accepted seasonally — call or dial 211 for current enrollment period',
    eligibility: 'Households at or below 60% of state median income. Priority to elderly, disabled, and families with young children.',
    description: 'Federally funded Low Income Home Energy Assistance Program helps pay heating and cooling costs. Apply through DSS or call 211 for help navigating the application.',
    website: 'https://dss.sc.gov/programs/liheap/',
    mapsUrl: null,
  },
  {
    id: 'united-way-211',
    name: '211 – Spartanburg Resource Helpline',
    category: 'utilities',
    address: null,
    zip: null,
    phone: '211',
    hours: '24/7',
    eligibility: 'Anyone in need. Free and confidential.',
    description: 'Dial 2-1-1 (or 877-211-3642) to reach a specialist who can connect you with resources for utilities, food, rent, healthcare, and more. Available 24/7 in English and Spanish.',
    website: 'https://www.uwpiedmont.org/211',
    mapsUrl: null,
  },

  // ── CLOTHING & HOUSEHOLD ──────────────────────────────────────────────────
  {
    id: 'salvation-army-thrift',
    name: 'Salvation Army Family Store',
    category: 'clothing',
    address: '1529 John B White Sr Blvd, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 576-6670',
    hours: 'Mon–Sat 9:00 AM – 6:00 PM',
    eligibility: 'Open to all. Free clothing vouchers available for those who cannot pay — ask social services.',
    description: 'Affordable clothing, furniture, and household goods. Free clothing and household vouchers available for qualified individuals — ask at the service desk, not the register.',
    website: 'https://centralsc.salvationarmy.org/spartanburg',
    mapsUrl: 'https://maps.google.com/?q=1529+John+B+White+Sr+Blvd+Spartanburg+SC+29301',
  },
  {
    id: 'goodwill-thrift-spartanburg',
    name: 'Goodwill Store & Donation Center',
    category: 'clothing',
    address: '1400 E Main St, Spartanburg, SC 29307',
    zip: '29307',
    phone: '(864) 583-3000',
    hours: 'Mon–Sat 9:00 AM – 9:00 PM · Sun 12:00 PM – 6:00 PM',
    eligibility: 'Open to all. No income requirements to shop.',
    description: 'Affordable clothing, shoes, furniture, and household items. Revenue supports free job training programs for people with barriers to employment in the Upstate.',
    website: 'https://www.goodwillsc.org',
    mapsUrl: 'https://maps.google.com/?q=1400+E+Main+St+Spartanburg+SC+29307',
  },
  {
    id: 'bethlehem-center-clothing',
    name: 'Bethlehem Center – Clothing Closet',
    category: 'clothing',
    address: '1066 W Main St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 585-0886',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income Spartanburg County residents. Call ahead to confirm availability.',
    description: 'Free clothing and basic household items for individuals and families in need. Part of Bethlehem Center\'s broader emergency assistance program.',
    website: 'https://www.bethlehemcenter.org',
    mapsUrl: 'https://maps.google.com/?q=1066+W+Main+St+Spartanburg+SC+29301',
  },
];
