const CATEGORIES = [
  { id: 'food',               label: 'Food',                icon: '🍽️' },
  { id: 'housing',            label: 'Housing',             icon: '🏠' },
  { id: 'healthcare',         label: 'Healthcare',          icon: '⚕️' },
  { id: 'mental-health',      label: 'Mental Health',       icon: '🧠' },
  { id: 'substance-recovery', label: 'Substance Recovery',  icon: '💊' },
  { id: 'employment',         label: 'Employment',          icon: '💼' },
  { id: 'transportation',     label: 'Transportation',      icon: '🚌' },
  { id: 'childcare',          label: 'Childcare',           icon: '👶' },
  { id: 'legal-aid',          label: 'Legal Aid',           icon: '⚖️' },
  { id: 'utilities',          label: 'Utilities Assistance',icon: '💡' },
  { id: 'clothing',           label: 'Clothing & Household',icon: '👕' },
  { id: 'seniors',            label: 'Senior Services',     icon: '🧓' },
  { id: 'shelters',           label: 'Shelters',            icon: '🛖' },
  { id: 'veterans',           label: 'Veterans',            icon: '🎖️' },
  { id: 'education',          label: 'Education & Library', icon: '📚' },
];

const RESOURCES = [
  // ── FOOD ──────────────────────────────────────────────────────────────────
  {
    id: 'greater-spartanburg-ministries',
    name: 'Greater Spartanburg Ministries',
    category: 'food',
    address: '680 Asheville Hwy, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 585-9371',
    hours: 'Food Pantry: Mon, Tue & Thu 9:30 AM – 11:30 AM (closed 2nd & 4th Tue) · Thrift Store: Mon–Sat 9:00 AM – 5:00 PM',
    eligibility: 'Spartanburg County residents in need. Bring ID and proof of address.',
    description: 'Provides dry, fresh, refrigerated, and frozen groceries from a food pantry open three days a week. On-site thrift store with affordable clothing and household items.',
    website: 'http://www.greaterspartanburgministries.org',
    mapsUrl: 'https://maps.google.com/?q=680+Asheville+Hwy+Spartanburg+SC+29303',
  },
  {
    id: 'broken-angels-landrum',
    name: 'Broken Angels Emergency Response',
    category: 'food',
    address: '211 W Rutherford St, Landrum, SC 29356',
    zip: '29356',
    phone: '(864) 608-1455',
    hours: 'Tue–Fri 9:30 AM – 4:00 PM · Sat 9:30 AM – 1:00 PM',
    eligibility: 'Open to all. Serves Landrum and surrounding communities — no residency requirement.',
    description: 'Nonprofit food bank and variety shop serving Landrum and surrounding Spartanburg County communities. Provides free food giveaways, supplies food to other pantries within 75 miles, and responds to local disasters with emergency food and essentials.',
    website: 'https://brokenangelssc.com',
    mapsUrl: 'https://maps.google.com/?q=211+W+Rutherford+St+Landrum+SC+29356',
  },
  {
    id: 'greer-community-ministries',
    name: 'Greer Community Ministries',
    category: 'food',
    address: '738 S Line St Ext, Greer, SC 29651',
    zip: '29651',
    phone: '(864) 877-1937',
    hours: 'Mon–Thu 8:00 AM – 4:00 PM · Fri 8:00 AM – 2:00 PM',
    eligibility: 'Residents of Greer, Lyman, Duncan, Wellford, Startex, Woodruff, Campobello, Inman, or Taylors. Bring valid ID.',
    description: 'Serves a wide swath of eastern Spartanburg County with a food pantry, Meals on Wheels, senior dining, and Sharon\'s Closet (free clothing). One of the few county resources explicitly covering Woodruff, Inman, and Wellford.',
    website: 'https://www.gcminc.org',
    mapsUrl: 'https://maps.google.com/?q=738+S+Line+St+Ext+Greer+SC+29651',
  },
  {
    id: 'helping-hands-woodruff',
    name: 'Helping Hands Ministries of Woodruff',
    category: 'food',
    address: '206 Chamblin St, Woodruff, SC 29388',
    zip: '29388',
    phone: '(864) 476-2401',
    hours: 'Food: Mon–Fri 10:00 AM – 12:30 PM · Food Boxes (Tue & Thu) · Clothing Closet: Wed 10:00 AM – Noon · Financial Help: Mon, Wed & Fri 10:00 AM – Noon',
    eligibility: 'Woodruff School District 4 residents. Bring proof of address.',
    description: 'Provides food three days a week, food boxes twice a week, a free clothing closet on Wednesdays, and limited financial assistance for rent, utilities, and life-sustaining prescriptions when funds are available.',
    website: 'https://hhow.org',
    mapsUrl: 'https://maps.google.com/?q=206+Chamblin+St+Woodruff+SC+29388',
  },
  {
    id: 'woodruff-soup-kitchen',
    name: 'Woodruff Area Soup Kitchen',
    category: 'food',
    address: '340 McArthur St, Woodruff, SC 29388',
    zip: '29388',
    phone: '(864) 476-3589',
    hours: 'Mon–Fri 11:30 AM – 12:30 PM',
    eligibility: 'Anyone in need is welcome. No ID or documentation required.',
    description: 'Free hot meals served every weekday in Woodruff. No questions asked — just show up.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=340+McArthur+St+Woodruff+SC+29388',
  },
  {
    id: 'lake-bowen-baptist-pantry',
    name: 'Lake Bowen Baptist Church Food Pantry',
    category: 'food',
    address: '404 Sugar Ridge Rd, Inman, SC 29349',
    zip: '29349',
    phone: '(864) 814-6280',
    hours: '4th Saturday of each month 9:00 AM – 11:00 AM',
    eligibility: 'Open to Inman-area residents in need.',
    description: 'Monthly community food pantry serving the Inman area of northern Spartanburg County.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=404+Sugar+Ridge+Rd+Inman+SC+29349',
  },
  {
    id: 'cowpens-first-baptist-pantry',
    name: 'Cowpens First Baptist Church Food Pantry',
    category: 'food',
    address: '108 W Church St, Cowpens, SC 29330',
    zip: '29330',
    phone: '(864) 463-4080',
    hours: '2nd, 3rd & 4th Tuesday of each month 10:00 AM – 11:00 AM',
    eligibility: 'Open to Cowpens-area residents in need.',
    description: 'Weekly food pantry serving the Cowpens community, open three Tuesdays a month.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=108+W+Church+St+Cowpens+SC+29330',
  },
  {
    id: 'spartanburg-area-food-bank',
    name: 'Spartanburg Area Food Bank',
    category: 'food',
    address: '355 Dupre Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 582-3576',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Open to Spartanburg County residents in need. No income verification required for most programs.',
    description: 'Distributes food through 100+ partner agencies across Spartanburg County. Provides emergency food boxes and connects families with local pantry partners closest to them.',
    website: 'https://www.spartanburgfoodbank.org',
    mapsUrl: 'https://maps.google.com/?q=355+Dupre+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'soup-kitchen-spartanburg',
    name: 'Spartanburg Soup Kitchen',
    category: 'food',
    address: '136 S Forest St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 585-0022',
    hours: 'Every day 7:30 AM – 2:00 PM',
    eligibility: 'Anyone in need is welcome. No ID or documentation required.',
    description: 'Serves free hot meals every day to anyone who shows up hungry. Also provides food boxes and connects guests with other social services in Spartanburg.',
    website: 'https://spartanburgsoupkitchen.org',
    mapsUrl: 'https://maps.google.com/?q=136+S+Forest+St+Spartanburg+SC+29306',
  },
  {
    id: 'total-ministries-spartanburg',
    name: 'Total Ministries of Spartanburg',
    category: 'food',
    address: '976 S Pine St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 585-9167',
    hours: 'Mon–Fri — call for current distribution hours (opens 9 AM)',
    eligibility: 'Open to individuals and families in need. Call ahead to confirm requirements.',
    description: 'Faith-based organization providing food distribution along with help for utilities and rent. Reviews highlight a friendly and helpful staff. A one-stop resource for multiple types of emergency assistance.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=976+S+Pine+St+Spartanburg+SC+29302',
  },
  {
    id: 'believers-fellowship-pantry',
    name: 'Believers Fellowship Food Pantry',
    category: 'food',
    address: '150 Marion Ave, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 573-5049',
    hours: 'Tue 9:00 AM — call for closing time and additional days',
    eligibility: 'Open to individuals and families in need. Call ahead.',
    description: 'Grocery pickup food pantry offering bagged or boxed groceries. No on-site meal service. Community members consistently praise the welcoming volunteers.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=150+Marion+Ave+Spartanburg+SC+29303',
  },
  {
    id: 'st-matthews-episcopal-pantry',
    name: "St. Matthew's Episcopal Church Food Pantry",
    category: 'food',
    address: '101 St Matthews Ln, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 576-0424',
    hours: 'Call for current pantry schedule',
    eligibility: 'Open to those in need. Described by visitors as welcoming and compassionate.',
    description: 'Food pantry operated through St. Matthew\'s Episcopal Church. Community members describe a warm, judgment-free environment. Call the church office for current pantry days and hours.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=101+St+Matthews+Ln+Spartanburg+SC+29301',
  },
  {
    id: 'ruths-gleanings',
    name: "Ruth's Gleanings",
    category: 'food',
    address: '147 Chapel St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 586-2840',
    hours: 'Mon 10:00 AM — call for full weekly schedule',
    eligibility: 'Open to the community. Low-cost produce — no income verification required to purchase.',
    description: 'Provides affordable fresh vegetables and produce at low cost to help community members eat healthier on a tight budget. A good supplement to pantry food boxes for fresh items.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=147+Chapel+St+Spartanburg+SC+29306',
  },
  {
    id: 'carpenters-table-foodbank',
    name: "The Carpenter's Table Foodbank",
    category: 'food',
    address: '5957 Reidville Rd, Moore, SC 29369',
    zip: '29369',
    phone: '(864) 486-8360',
    hours: 'Sat 8:00 AM — call for full schedule and closing time',
    eligibility: 'Open to all in need. No income verification required.',
    description: 'Highly regarded food bank serving the Moore, Reidville, and Duncan corridor of Spartanburg County. Consistently praised by community members for a caring, helpful atmosphere. Call ahead to confirm current distribution times.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=5957+Reidville+Rd+Moore+SC+29369',
  },
  {
    id: 'second-harvest-food-bank',
    name: 'Second Harvest Food Bank',
    category: 'food',
    address: '1503 Old Converse Rd, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(704) 293-1755',
    hours: 'Mon–Fri — opens 7:00 AM (call to confirm distribution schedule)',
    eligibility: 'Food distributed through partner agencies. Call to determine if this location serves individuals directly or connects you to a nearby pantry partner.',
    description: 'Regional food bank with a Spartanburg location on Old Converse Rd. Distributes food through a network of partner pantries. Call to confirm whether walk-in distribution is available or to be directed to the nearest partner pantry.',
    website: 'https://www.secondharvestmetrolina.org',
    mapsUrl: 'https://maps.google.com/?q=1503+Old+Converse+Rd+Spartanburg+SC+29302',
  },
  {
    id: 'regenesis-health-care',
    name: 'ReGenesis Health Care',
    category: 'healthcare',
    address: '301 Crescent Ave, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-2411',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM (multiple locations — call for specific hours)',
    eligibility: 'Open to all. Accepts all insurance including Medicaid and Medicare. Sliding fee scale for uninsured patients based on income.',
    description: 'Federally Qualified Health Center with multiple Spartanburg locations offering primary care, dental, behavioral health, and pharmacy services. No one turned away for inability to pay. Also has locations on N Pine St (dental), S Church St, and Langdon St.',
    website: 'https://www.myrhc.org',
    mapsUrl: 'https://maps.google.com/?q=301+Crescent+Ave+Spartanburg+SC+29306',
  },
  {
    id: 'st-lukes-free-medical-clinic',
    name: "St. Luke's Free Medical Clinic",
    category: 'healthcare',
    address: '162 N Dean St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 542-2273',
    hours: 'By appointment only — call to schedule. New patient applications: Mon 10am–1pm & Thu 1–4pm.',
    eligibility: 'Uninsured adults who cannot afford care. Appointment required — walk-ins not accepted.',
    description: 'Volunteer-run free medical clinic providing primary care, chronic disease management, and prescription assistance to uninsured adults. Call to confirm current clinic schedule before visiting. Satellite clinic at 101 St Matthews Ln (call for hours).',
    website: 'https://www.slfmc.org',
    mapsUrl: 'https://maps.google.com/?q=162+N+Dean+St+Spartanburg+SC+29302',
  },

  // ── HOUSING ───────────────────────────────────────────────────────────────
  {
    id: 'miracle-hill-rescue-mission',
    name: 'Miracle Hill Rescue Mission',
    category: 'shelters',
    address: '189 N Forest St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 583-1628',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM · Call for emergency shelter intake',
    eligibility: 'Men, women, and mothers with young children experiencing homelessness. No ID required for crisis shelter.',
    description: '94-bed emergency shelter providing food, clothing, and case management. The Crisis Shelter Program offers short-term stays; the New Life Program provides longer-term comprehensive care including life skills, education, and discipleship. Free on-site medical, dental, and vision clinic available to guests and the community.',
    website: 'https://miraclehill.org/shelters/spartanburg-rescue-mission/',
    mapsUrl: 'https://maps.google.com/?q=189+N+Forest+St+Spartanburg+SC+29301',
  },
  {
    id: 'union-mission-spartanburg',
    name: 'Union Mission of Spartanburg',
    category: 'shelters',
    address: '144 Union St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 582-7553',
    hours: 'Open 24/7 for emergency intake',
    eligibility: 'Adult men needing emergency shelter. Women and family shelter available — call for current space.',
    description: 'Emergency shelter, transitional housing, daily meals, and recovery programs for homeless individuals. Operates separate men\'s and women\'s facilities with wraparound support services.',
    website: 'https://www.unionmission.org',
    mapsUrl: 'https://maps.google.com/?q=144+Union+St+Spartanburg+SC+29302',
  },
  {
    id: 'spartanburg-housing-authority',
    name: 'Spartanburg Housing Authority',
    category: 'housing',
    address: '170 Arch St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 598-6000',
    hours: 'Mon–Thu 8:30 AM – 5:30 PM · Fri 8:30 AM – Noon',
    eligibility: 'Low-income families, elderly, and disabled individuals. Income limits apply. Waiting lists may be in effect — call to check status.',
    description: 'Manages public housing units and administers Housing Choice Vouchers (Section 8) to help low-income residents afford safe housing in Spartanburg.',
    website: 'https://www.spartanburghousing.org',
    mapsUrl: 'https://maps.google.com/?q=170+Arch+St+Spartanburg+SC+29303',
  },
  {
    id: 'safe-homes-spartanburg',
    name: 'Project R.E.S.T. – Domestic Violence & Sexual Assault Services',
    category: 'shelters',
    address: '236 Union St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '1-800-273-5066',
    hours: '24/7 Crisis Hotline · Office Mon–Fri 8:30 AM – 5:00 PM: (864) 583-9803',
    eligibility: 'Survivors of domestic violence and sexual assault in Spartanburg, Cherokee, and Union Counties. Services are free and confidential.',
    description: 'Formerly known as SAFE Homes. Provides 41 emergency and 9 transitional shelter beds for DV survivors, crisis intervention, legal advocacy, safety planning, court assistance, and emergency cell phones. Shelter location is confidential — call the hotline. Serves Spartanburg, Cherokee, and Union Counties.',
    website: 'https://projectrest.org',
    mapsUrl: null,
  },
  {
    id: 'bethlehem-center',
    name: 'Bethlehem Center',
    category: 'housing',
    address: '1066 W Main St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 585-0886',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income families and individuals in Spartanburg County. Documentation required — call ahead.',
    description: 'Community center providing emergency rental and utility assistance, food, clothing, and case management to stabilize families in crisis and prevent homelessness.',
    website: 'https://www.bethlehemcenter.org',
    mapsUrl: 'https://maps.google.com/?q=1066+W+Main+St+Spartanburg+SC+29301',
  },

  // ── HEALTHCARE ────────────────────────────────────────────────────────────
  {
    id: 'spartanburg-community-health-centers',
    name: 'Spartanburg Community Health Centers',
    category: 'healthcare',
    address: '484 Southport Rd, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-1751',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Open to all. Sliding fee scale based on income. Medicaid, Medicare, and uninsured patients all welcome.',
    description: 'Federally Qualified Health Center (FQHC) offering primary care, dental, behavioral health, and pharmacy services. No one is turned away for inability to pay.',
    website: 'https://www.schealthlink.com',
    mapsUrl: 'https://maps.google.com/?q=484+Southport+Rd+Spartanburg+SC+29306',
  },
  {
    id: 'free-medical-clinic-upstate',
    name: 'Free Medical Clinic of the Upstate',
    category: 'healthcare',
    address: '174 S Forest St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 576-6566',
    hours: 'Tue & Thu evenings — call for current schedule',
    eligibility: 'Uninsured adults who meet income guidelines and live or work in Spartanburg County.',
    description: 'Volunteer-run clinic providing free primary care, lab work, and prescription medications to uninsured working adults who do not qualify for Medicaid.',
    website: 'https://www.fmcupstate.org',
    mapsUrl: 'https://maps.google.com/?q=174+S+Forest+St+Spartanburg+SC+29306',
  },
  {
    id: 'spartanburg-regional-medical-center',
    name: 'Spartanburg Regional Medical Center',
    category: 'healthcare',
    address: '101 E Wood St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 560-6000',
    hours: 'Emergency Room open 24/7',
    eligibility: 'Emergency care available to all regardless of insurance or ability to pay. Financial assistance programs available.',
    description: 'Full-service regional hospital with 24/7 emergency care. Charity care and financial assistance programs are available — ask the billing department or a patient advocate.',
    website: 'https://www.spartanburgregional.com',
    mapsUrl: 'https://maps.google.com/?q=101+E+Wood+St+Spartanburg+SC+29303',
  },

  // ── VETERANS ──────────────────────────────────────────────────────────────
  {
    id: 'va-spartanburg-cboc',
    name: 'VA Community-Based Outpatient Clinic – Spartanburg',
    category: 'veterans',
    address: '350 Serpentine Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 299-1600',
    hours: 'Mon–Fri 8:00 AM – 4:30 PM',
    eligibility: 'Enrolled veterans. If not yet enrolled, call or visit VA.gov to apply — many veterans qualify even without a disability rating.',
    description: 'VA outpatient clinic providing primary care, mental health, and preventive services to Spartanburg-area veterans. Avoids the need to travel to the full VA Medical Center in Columbia or Augusta. Call to enroll or schedule an appointment.',
    website: 'https://www.va.gov/columbia-south-carolina-health-care/locations/spartanburg-va-clinic/',
    mapsUrl: 'https://maps.google.com/?q=350+Serpentine+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'sc-veterans-affairs',
    name: 'SC Department of Veterans Affairs – Spartanburg',
    category: 'veterans',
    address: '366 N Church St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 596-2563',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'SC veterans and their dependents. No service-connected disability required for most services.',
    description: 'State veterans affairs office helping with VA benefit claims, disability ratings, pension applications, education benefits (GI Bill), home loans, and burial benefits. Free assistance navigating the federal VA system from accredited claims agents.',
    website: 'https://scdva.sc.gov',
    mapsUrl: 'https://maps.google.com/?q=366+N+Church+St+Spartanburg+SC+29303',
  },
  {
    id: 'vfw-spartanburg',
    name: 'Veterans of Foreign Wars (VFW) – Spartanburg Posts',
    category: 'veterans',
    address: 'Multiple posts in Spartanburg County',
    zip: '29301',
    phone: '(864) 585-8634',
    hours: 'Varies by post — call for hours and services',
    eligibility: 'Veterans who served in overseas combat. Companion post programs available to all veterans.',
    description: 'Local VFW posts offer emergency financial assistance to veterans in crisis, camaraderie, and help navigating VA benefits. Some posts run food pantries and clothing assistance for veterans and their families. Call to find the post nearest you.',
    website: 'https://www.vfw.org',
    mapsUrl: null,
  },

  // ── MENTAL HEALTH ─────────────────────────────────────────────────────────
  {
    id: 'nami-spartanburg',
    name: 'NAMI – National Alliance on Mental Illness',
    category: 'mental-health',
    address: null,
    zip: '29301',
    phone: '1-800-950-6264',
    hours: 'Helpline: Mon–Fri 10:00 AM – 10:00 PM ET · Text "NAMI" to 741741 anytime',
    eligibility: 'Anyone affected by mental illness — individuals, family members, and caregivers. All support programs are free.',
    description: 'Free peer support groups, family education programs (Family-to-Family, NAMI Basics), and a crisis helpline. Call the NAMI Helpline to find local support groups and free classes in the Spartanburg area. Also offers NAMI Peer-to-Peer, a free program taught by and for people with mental illness.',
    website: 'https://www.nami.org/Support-Education/NAMI-HelpLine',
    mapsUrl: null,
  },
  {
    id: 'spartanburg-community-mental-health',
    name: 'Spartanburg Area Mental Health Center',
    category: 'mental-health',
    address: '250 Dewey Ave, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 585-0366',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM · 24/7 Crisis Line: (800) 277-1366',
    eligibility: 'Open to all Spartanburg County residents. Sliding fee scale. Medicaid accepted. No one turned away.',
    description: 'State-funded center offering outpatient therapy, psychiatric services, crisis intervention, and case management. Specializes in serving people with limited income or no insurance. 24/7 crisis line: (800) 277-1366.',
    website: 'https://sparmhc.org',
    mapsUrl: 'https://maps.google.com/?q=250+Dewey+Ave+Spartanburg+SC+29303',
  },
  {
    id: '988-crisis-lifeline',
    name: '988 Suicide & Crisis Lifeline',
    category: 'mental-health',
    address: null,
    zip: null,
    phone: '988',
    hours: '24/7 — call or text anytime',
    eligibility: 'Anyone in emotional distress or suicidal crisis. Free and confidential.',
    description: 'Call or text 988 to reach a trained crisis counselor. Available 24 hours a day, every day. Chat also available at 988lifeline.org. Deaf/hard of hearing: use your relay service.',
    website: 'https://988lifeline.org',
    mapsUrl: null,
  },
  {
    id: 'crisis-text-line',
    name: 'Crisis Text Line',
    category: 'mental-health',
    address: null,
    zip: null,
    phone: 'Text HOME to 741741',
    hours: '24/7',
    eligibility: 'Anyone in crisis. Free, confidential, and text-based.',
    description: 'Text HOME to 741741 to connect with a trained crisis counselor via text message. Good option if you cannot make a phone call or prefer to text.',
    website: 'https://www.crisistextline.org',
    mapsUrl: null,
  },

  {
    id: 'shepherds-center-spartanburg',
    name: "Shepherd's Center of Spartanburg",
    category: 'seniors',
    address: '393 E Main St, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 585-1999',
    hours: 'Mon–Fri — call for current class and program schedule',
    eligibility: 'Active seniors in Spartanburg. Most programs are free or low-cost.',
    description: 'Provides seniors with programs for physical fitness (line dancing, aerobics, tai chi), lifelong learning classes, mental wellness activities, and volunteer opportunities. Focused on helping older adults stay active, connected, and independent.',
    website: 'https://spartanburgshepherdcenter.org',
    mapsUrl: 'https://maps.google.com/?q=393+E+Main+St+Spartanburg+SC+29302',
  },

  // ── SUBSTANCE RECOVERY ────────────────────────────────────────────────────
  {
    id: 'beckman-center',
    name: 'Beckman Center for Mental Health Services',
    category: 'substance-recovery',
    address: '1 Beckman Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 582-7588',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Adults with substance use disorders. Medicaid, Medicare, and self-pay on sliding scale.',
    description: 'Outpatient substance use treatment including individual and group counseling, medication-assisted treatment (MAT), and recovery support services.',
    website: null,
    mapsUrl: 'https://maps.google.com/?q=1+Beckman+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'samhsa-helpline',
    name: 'SAMHSA National Helpline',
    category: 'substance-recovery',
    address: null,
    zip: null,
    phone: '1-800-662-4357',
    hours: '24/7, 365 days a year',
    eligibility: 'Anyone struggling with substance use or mental health. Free, confidential, English and Spanish.',
    description: 'Dial 1-800-662-HELP for free, confidential referrals to local treatment facilities, support groups, and community-based organizations. Available in English and Spanish.',
    website: 'https://www.samhsa.gov/find-help/national-helpline',
    mapsUrl: null,
  },
  {
    id: 'na-spartanburg',
    name: 'Narcotics Anonymous – Spartanburg Area',
    category: 'substance-recovery',
    address: 'Multiple meeting locations across Spartanburg',
    zip: '29301',
    phone: '1-800-974-0062',
    hours: 'Meetings 7 days a week — visit the meeting finder for schedule',
    eligibility: 'Anyone with a desire to stop using drugs. No fees, no requirements, no minimum "clean time" needed.',
    description: 'Free peer support meetings for people recovering from drug addiction of any kind. The Piedmont Area NA (PANA) serves the Spartanburg region with multiple meetings every day of the week. Use the online meeting finder or call the helpline to find a meeting near you — including online/phone meetings.',
    website: 'https://www.na.org/meetingsearch/',
    mapsUrl: null,
  },
  {
    id: 'aa-spartanburg',
    name: 'Alcoholics Anonymous – Spartanburg',
    category: 'substance-recovery',
    address: 'Multiple meeting locations in Spartanburg',
    zip: '29301',
    phone: '(864) 582-9573',
    hours: 'Meetings 7 days a week — see website for schedule',
    eligibility: 'Anyone with a desire to stop drinking. No fees, no requirements.',
    description: 'AA offers free peer support meetings throughout Spartanburg. Call the local intergroup or use the meeting finder to locate a meeting near you — any day of the week. Also see our <a href="meetings.html">AA &amp; NA Meeting Finder page</a> for side-by-side resources.',
    website: 'https://www.aaspartanburg.org',
    mapsUrl: null,
  },

  // ── EMPLOYMENT ────────────────────────────────────────────────────────────
  {
    id: 'sc-works-spartanburg',
    name: 'SC Works Spartanburg',
    category: 'employment',
    address: '145 N Church St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 764-1966',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'All job seekers. Services are free.',
    description: 'State workforce center with job listings, resume assistance, skills training funding, unemployment support, and access to computers and internet. Drop-ins welcome.',
    website: 'https://scworksupstate.com',
    mapsUrl: 'https://maps.google.com/?q=145+N+Church+St+Spartanburg+SC+29306',
  },
  {
    id: 'sc-vocational-rehab',
    name: 'SC Vocational Rehabilitation – Spartanburg',
    category: 'employment',
    address: '170 Ottaray Ave, Spartanburg, SC 29302',
    zip: '29302',
    phone: '(864) 585-3681',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Individuals with a physical, mental, learning, or behavioral disability who want to work. No income limit to apply.',
    description: 'Free job preparation and placement services for people with disabilities. Provides career counseling, job training funding, assistive technology, supported employment, and help connecting with employers who hire people with disabilities. Completely free to individuals who qualify.',
    website: 'https://www.scvrd.net',
    mapsUrl: 'https://maps.google.com/?q=170+Ottaray+Ave+Spartanburg+SC+29302',
  },
  {
    id: 'goodwill-job-training',
    name: 'Goodwill – Job Training & Placement',
    category: 'employment',
    address: '424 W Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 583-3000',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Anyone facing barriers to employment. Free programs.',
    description: 'Free job skills training, digital literacy classes, and employment placement services. Especially focused on individuals with disabilities, gaps in work history, or past criminal records.',
    website: 'https://www.goodwillsc.org',
    mapsUrl: 'https://maps.google.com/?q=424+W+Main+St+Spartanburg+SC+29306',
  },

  // ── TRANSPORTATION ────────────────────────────────────────────────────────
  {
    id: 'sparta-transit',
    name: 'SPARTA – Spartanburg Area Transit',
    category: 'transportation',
    address: '170 S Henry St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 327-2222',
    hours: 'Mon–Sat 6:00 AM – 7:00 PM (route dependent)',
    eligibility: 'Open to all. Reduced fares for seniors (65+) and riders with disabilities. Paratransit available for eligible riders.',
    description: 'Public bus system with fixed routes through Spartanburg city and county. Paratransit (door-to-door) service available for qualified riders who cannot use fixed-route buses.',
    website: 'https://www.ridesparta.com',
    mapsUrl: 'https://maps.google.com/?q=170+S+Henry+St+Spartanburg+SC+29306',
  },

  // ── CHILDCARE ─────────────────────────────────────────────────────────────
  {
    id: 'sc-wic-spartanburg',
    name: 'SC WIC – Women, Infants & Children',
    category: 'childcare',
    address: 'Multiple Spartanburg County clinic sites — call for nearest location',
    zip: '29301',
    phone: '1-800-277-4312',
    hours: 'Mon–Fri — call for clinic hours at your nearest site',
    eligibility: 'Pregnant or postpartum women, breastfeeding mothers, infants, and children under 5 who meet income guidelines (up to 185% of federal poverty level). Citizenship not required.',
    description: 'Provides monthly food benefits (milk, eggs, produce, whole grains, baby formula), nutrition counseling, and breastfeeding support. Also links families to healthcare and other services. Call the toll-free line to find the WIC office closest to you in Spartanburg County.',
    website: 'https://scdhec.gov/health/women-infants-children-wic',
    mapsUrl: null,
  },
  {
    id: 'head-start-spartanburg',
    name: 'Head Start & Early Head Start',
    category: 'childcare',
    address: 'Multiple sites across Spartanburg County — call for enrollment',
    zip: '29301',
    phone: '(864) 585-5282',
    hours: 'Mon–Fri during school year · Call for schedule and enrollment dates',
    eligibility: 'Children ages birth–5 in families at or below the federal poverty level. Pregnant women may qualify for Early Head Start.',
    description: 'Free federally funded preschool and early childhood program providing education, health screenings, nutrition, and family support services. Cherokee Foothills Child Development runs Head Start sites in Spartanburg County. Call for the location nearest you and to get on the enrollment list.',
    website: 'https://www.acf.hhs.gov/ohs/about/head-start',
    mapsUrl: null,
  },
  {
    id: 'dss-spartanburg',
    name: 'Spartanburg DSS – Benefits & Child Services',
    category: 'childcare',
    address: '200 Magnolia St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 596-2770',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income families with children. Income guidelines apply for childcare subsidies.',
    description: 'Department of Social Services office handling childcare subsidy vouchers, SNAP food assistance, Medicaid enrollment, TANF cash assistance, and child protective services.',
    website: 'https://dss.sc.gov',
    mapsUrl: 'https://maps.google.com/?q=200+Magnolia+St+Spartanburg+SC+29306',
  },
  {
    id: 'child-abuse-prevention-association',
    name: 'CAPA – Child Abuse Prevention Association',
    category: 'childcare',
    address: '167 W Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 582-3252',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Families with children in Spartanburg County. Income-based programs available.',
    description: 'Parenting education, family support services, home visiting programs, and crisis assistance designed to prevent child abuse and help families stay safely together.',
    website: 'https://www.capasc.org',
    mapsUrl: 'https://maps.google.com/?q=167+W+Main+St+Spartanburg+SC+29306',
  },

  // ── LEGAL AID ─────────────────────────────────────────────────────────────
  {
    id: 'palmetto-legal-aid',
    name: 'SC Legal Services – Spartanburg',
    category: 'legal-aid',
    address: '148 E Main St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(888) 346-5592',
    hours: 'Mon–Wed & Fri 8:30 AM – 5:00 PM · Thu 8:30 AM – 7:00 PM',
    eligibility: 'Households at or below 125% of federal poverty level in Spartanburg County.',
    description: 'Free civil legal representation for low-income residents. Handles evictions, foreclosure prevention, domestic violence protection orders, public benefits denials, and family law matters.',
    website: 'https://sclegal.org',
    mapsUrl: 'https://maps.google.com/?q=148+E+Main+St+Spartanburg+SC+29306',
  },
  {
    id: 'sc-bar-pro-bono',
    name: 'SC Bar Pro Bono Program',
    category: 'legal-aid',
    address: 'Statewide — call for Spartanburg referrals',
    zip: '29301',
    phone: '1-800-868-2284',
    hours: 'Mon–Fri 9:00 AM – 5:00 PM',
    eligibility: 'Low-income individuals who need civil legal help and do not qualify for SC Legal Services.',
    description: 'Connects low-income South Carolinians with volunteer attorneys for free legal advice and representation. Call the statewide hotline and ask for Spartanburg referrals.',
    website: 'https://www.scbar.org/public/get-legal-help/pro-bono-program/',
    mapsUrl: null,
  },

  // ── UTILITIES ASSISTANCE ──────────────────────────────────────────────────
  {
    id: 'salvation-army-spartanburg',
    name: 'Salvation Army of Spartanburg',
    category: 'utilities',
    address: '1529 John B White Sr Blvd, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 576-6670',
    hours: 'Mon–Fri 9:00 AM – 5:00 PM',
    eligibility: 'Spartanburg County residents in financial crisis. Income verification and ID required.',
    description: 'Emergency utility assistance (electric, gas, water), rent assistance, and food boxes for residents in crisis. Limited funds available — call early in the month for best availability.',
    website: 'https://centralsc.salvationarmy.org/spartanburg',
    mapsUrl: 'https://maps.google.com/?q=1529+John+B+White+Sr+Blvd+Spartanburg+SC+29301',
  },
  {
    id: 'middle-tyger-community-center',
    name: 'Middle Tyger Community Center',
    category: 'utilities',
    address: '84 Groce Rd, Lyman, SC 29365',
    zip: '29365',
    phone: '(864) 439-7760',
    hours: 'Mon–Fri 8:00 AM – 5:00 PM',
    eligibility: 'Spartanburg County residents in need. Call ahead for specific program requirements.',
    description: 'Nonprofit serving the Lyman/eastern Spartanburg County area with a food pantry, emergency utility assistance, case management, crisis intervention, and family support services. One-stop resource for residents in the I-85 corridor communities.',
    website: 'https://www.middletyger.org',
    mapsUrl: 'https://maps.google.com/?q=84+Groce+Rd+Lyman+SC+29365',
  },
  {
    id: 'sc-thrive',
    name: 'SC Thrive – Benefits Enrollment Help',
    category: 'utilities',
    address: null,
    zip: null,
    phone: '1-800-726-8774',
    hours: 'Mon–Fri 9:00 AM – 5:00 PM',
    eligibility: 'Any SC resident who needs help applying for public benefits. Free and confidential.',
    description: 'Free, confidential help applying for SNAP food stamps, Medicaid, CHIP, WIC, LIHEAP, and other public benefits. Trained assisters screen you for all programs you may qualify for and help you complete applications correctly. Available by phone or at partner community locations.',
    website: 'https://scthrive.org',
    mapsUrl: null,
  },
  {
    id: 'vita-tax-prep',
    name: 'VITA – Free Tax Return Preparation',
    category: 'utilities',
    address: 'Spartanburg County sites — call 211 for current locations',
    zip: '29301',
    phone: '211',
    hours: 'January – April · Call 211 for current Spartanburg site schedule',
    eligibility: 'Households earning roughly $67,000 or less per year. Bring ID, Social Security cards, and all tax documents.',
    description: 'IRS-sponsored Volunteer Income Tax Assistance prepares and e-files your federal and SC state returns for free. Especially valuable for families claiming the Earned Income Tax Credit (EITC), which can be worth $7,000+. Call 211 or visit irs.gov/vita to find a Spartanburg site each tax season.',
    website: 'https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers',
    mapsUrl: null,
  },
  {
    id: 'sc-liheap',
    name: 'SC LIHEAP – Energy Bill Assistance',
    category: 'utilities',
    address: 'Apply at DSS: 200 Magnolia St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(800) 311-7220',
    hours: 'Applications accepted seasonally — call or dial 211 for current enrollment period',
    eligibility: 'Households at or below 60% of state median income. Priority to elderly, disabled, and families with young children.',
    description: 'Federally funded Low Income Home Energy Assistance Program helps pay heating and cooling costs. Apply through DSS or call 211 for help navigating the application.',
    website: 'https://dss.sc.gov/programs/liheap/',
    mapsUrl: null,
  },
  {
    id: 'united-way-211',
    name: '211 – Spartanburg Resource Helpline',
    category: 'utilities',
    address: null,
    zip: null,
    phone: '211',
    hours: '24/7',
    eligibility: 'Anyone in need. Free and confidential.',
    description: 'Dial 2-1-1 (or 877-211-3642) to reach a specialist who can connect you with resources for utilities, food, rent, healthcare, and more. Available 24/7 in English and Spanish.',
    website: 'https://www.uwpiedmont.org/211',
    mapsUrl: null,
  },

  // ── CLOTHING & HOUSEHOLD ──────────────────────────────────────────────────
  {
    id: 'salvation-army-thrift',
    name: 'Salvation Army Family Store',
    category: 'clothing',
    address: '1529 John B White Sr Blvd, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 576-6670',
    hours: 'Mon–Sat 9:00 AM – 6:00 PM',
    eligibility: 'Open to all. Free clothing vouchers available for those who cannot pay — ask social services.',
    description: 'Affordable clothing, furniture, and household goods. Free clothing and household vouchers available for qualified individuals — ask at the service desk, not the register.',
    website: 'https://centralsc.salvationarmy.org/spartanburg',
    mapsUrl: 'https://maps.google.com/?q=1529+John+B+White+Sr+Blvd+Spartanburg+SC+29301',
  },
  {
    id: 'goodwill-thrift-spartanburg',
    name: 'Goodwill Store & Donation Center',
    category: 'clothing',
    address: '1400 E Main St, Spartanburg, SC 29307',
    zip: '29307',
    phone: '(864) 583-3000',
    hours: 'Mon–Sat 9:00 AM – 9:00 PM · Sun 12:00 PM – 6:00 PM',
    eligibility: 'Open to all. No income requirements to shop.',
    description: 'Affordable clothing, shoes, furniture, and household items. Revenue supports free job training programs for people with barriers to employment in the Upstate.',
    website: 'https://www.goodwillsc.org',
    mapsUrl: 'https://maps.google.com/?q=1400+E+Main+St+Spartanburg+SC+29307',
  },
  // ── SHELTERS ──────────────────────────────────────────────────────────────
  {
    id: 'a-way-home-spartanburg',
    name: 'A Way Home – Family Shelter',
    category: 'shelters',
    address: '458 N Church St, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 582-6737',
    hours: 'Office 8:30 AM – 5:00 PM · Client intake 4:00 PM · Emergency intake 24/7',
    eligibility: 'Families experiencing homelessness — couples with or without children, single mothers, single fathers, and grandparents/legal guardians with children.',
    description: 'Short-term emergency shelter with wraparound support for homeless families. Provides safe shelter, daily meals, case management, and help moving toward stable permanent housing. Operated by A Place to Call Home in partnership with The Faith Initiative to End Child Poverty.',
    website: 'https://www.aptchspartanburg.org/a-way-home',
    mapsUrl: 'https://maps.google.com/?q=458+N+Church+St+Spartanburg+SC+29303',
  },
  {
    id: 'divinity-care-facility',
    name: 'Divinity Care Facility',
    category: 'shelters',
    address: '446 Arch St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 948-9700',
    hours: 'Call for intake hours',
    eligibility: 'Homeless men. No ID required to enter.',
    description: 'Christian-based emergency shelter for homeless men operating in Spartanburg since 1996. Provides food, shelter, job skills training, life skills classes, and faith-based support programs for men with nowhere else to turn.',
    website: 'https://divinitycare.wordpress.com',
    mapsUrl: 'https://maps.google.com/?q=446+Arch+St+Spartanburg+SC+29301',
  },

  // ── SENIOR SERVICES ──────────────────────────────────────────────────────
  {
    id: 'spartanburg-council-on-aging',
    name: 'Spartanburg Council on Aging – 50+ Wellness',
    category: 'seniors',
    address: 'Multiple sites county-wide — call for location nearest you',
    zip: '29301',
    phone: '(864) 804-5813',
    hours: 'Sites meet multiple days per week 8:30 AM – 1:00 PM — call for schedule',
    eligibility: 'Spartanburg County residents age 50 and older. Programs are free.',
    description: 'Free group meetings held at sites across the county where seniors enjoy activities, guest speakers, and a shared meal. Transportation to and from sites can be arranged for those who cannot drive. Funded through county and Appalachian Council of Governments grants.',
    website: 'https://www.spartanburgparks.org/151/50-Wellness-Programs',
    mapsUrl: null,
  },
  {
    id: 'fifty-upstate',
    name: 'Fifty Upstate – Senior Resource Hub',
    category: 'seniors',
    address: null,
    zip: '29301',
    phone: '(864) 621-9738',
    hours: 'Mon–Fri — call for current hours',
    eligibility: 'Spartanburg County residents age 50 and older.',
    description: 'Local hub connecting seniors to congregate meal sites, transportation, activities, and county aging services. A good first call if you are not sure what programs are available in your area of the county.',
    website: 'https://fiftyupstate.org',
    mapsUrl: null,
  },
  {
    id: 'help-for-our-elderly',
    name: 'Help for Our Elderly',
    category: 'seniors',
    address: '2375 E Main St, Unit A-311, Spartanburg, SC 29307',
    zip: '29307',
    phone: '(864) 308-8388',
    hours: 'Mon–Thu 10:00 AM – 3:00 PM',
    eligibility: 'Seniors, disabled individuals, and underserved residents in Spartanburg.',
    description: 'Provides free everyday household and cleaning supplies — laundry detergent, dish soap, mops, sponges, and more — to seniors and disabled individuals who struggle to afford basic necessities.',
    website: 'https://helpforourelderly.org',
    mapsUrl: 'https://maps.google.com/?q=2375+E+Main+St+Spartanburg+SC+29307',
  },
  {
    id: 'appalachian-council-aging',
    name: 'Appalachian Council of Governments – Area Agency on Aging',
    category: 'seniors',
    address: null,
    zip: '29301',
    phone: '1-800-434-4036',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Seniors in Spartanburg, Cherokee, and Union counties. Most programs target those 60 and older.',
    description: 'The federally designated Area Agency on Aging for the Upstate region. Coordinates in-home care, nutrition programs, caregiver support, transportation, legal assistance, and other services for older adults. Call the toll-free number to find out what you qualify for.',
    website: 'https://www.scacog.org/aging-services',
    mapsUrl: null,
  },
  {
    id: 'getcaresc',
    name: 'GetCareSC – SC Aging Services Navigator',
    category: 'seniors',
    address: null,
    zip: null,
    phone: '1-800-868-9095',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Any South Carolina senior or caregiver looking for services.',
    description: 'Free statewide service of the SC Department on Aging. Helps seniors and families find assisted living, in-home care, transportation, financial assistance, and other aging services. Can be searched online or by phone.',
    website: 'https://www.getcaresc.com',
    mapsUrl: null,
  },
  {
    id: 'mobile-meals-spartanburg',
    name: 'Mobile Meals of Spartanburg',
    category: 'seniors',
    address: 'Delivers to Spartanburg County',
    zip: '29301',
    phone: '(864) 573-0015',
    hours: 'Mon–Fri delivery (call to enroll)',
    eligibility: 'Homebound seniors and adults with disabilities who cannot prepare meals independently.',
    description: 'Delivers hot, nutritious meals to homebound seniors and disabled adults throughout Spartanburg County. Volunteer drivers also provide a friendly check-in with each delivery.',
    website: null,
    mapsUrl: null,
  },

  // ── EDUCATION & LIBRARY ───────────────────────────────────────────────────
  {
    id: 'spartanburg-county-library',
    name: 'Spartanburg County Public Library',
    category: 'education',
    address: '151 S Church St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 596-3505',
    hours: 'Mon–Thu 9:00 AM – 8:00 PM · Fri–Sat 9:00 AM – 5:00 PM · Sun 1:00 PM – 5:00 PM',
    eligibility: 'Open to all. Free library card with SC ID or proof of address. Computer and internet access requires no card.',
    description: 'Free computers, high-speed internet, printing, scanning, and fax. Job search resources, GED prep materials, notary services, and connections to social services. Multiple branch locations across Spartanburg County — call for the branch nearest you.',
    website: 'https://www.spartanburglibraries.org',
    mapsUrl: 'https://maps.google.com/?q=151+S+Church+St+Spartanburg+SC+29306',
  },
  {
    id: 'spartanburg-community-college',
    name: 'Spartanburg Community College – Workforce Programs',
    category: 'education',
    address: '107 Community College Dr, Spartanburg, SC 29303',
    zip: '29303',
    phone: '(864) 592-4600',
    hours: 'Mon–Thu 8:00 AM – 6:00 PM · Fri 8:00 AM – 5:00 PM',
    eligibility: 'Open to all adults. Financial aid, Pell grants, and workforce scholarships available for qualifying students.',
    description: 'Offers workforce training, GED/HiSET preparation, adult literacy, and short-term certificate programs in high-demand fields like healthcare, manufacturing, IT, and welding. Many programs qualify for free or reduced tuition through WIOA funding. Call the Continuing Education office for no-cost workforce training options.',
    website: 'https://www.sccsc.edu',
    mapsUrl: 'https://maps.google.com/?q=107+Community+College+Dr+Spartanburg+SC+29303',
  },
  {
    id: 'literacy-volunteers-spartanburg',
    name: 'Spartanburg Literacy Council',
    category: 'education',
    address: '151 S Church St, Spartanburg, SC 29306',
    zip: '29306',
    phone: '(864) 585-7244',
    hours: 'Mon–Fri 8:30 AM – 4:30 PM · Tutoring by appointment',
    eligibility: 'Adults reading below a 6th-grade level or who want to earn a GED/HiSET. ESL classes available for non-native English speakers.',
    description: 'Free one-on-one and small-group tutoring for adults to improve basic reading, writing, and math skills. Also offers GED preparation classes and ESL (English as a Second Language) instruction. All services are free and confidential.',
    website: 'https://spartanburgliteracy.org',
    mapsUrl: 'https://maps.google.com/?q=151+S+Church+St+Spartanburg+SC+29306',
  },

  {
    id: 'bethlehem-center-clothing',
    name: 'Bethlehem Center – Clothing Closet',
    category: 'clothing',
    address: '1066 W Main St, Spartanburg, SC 29301',
    zip: '29301',
    phone: '(864) 585-0886',
    hours: 'Mon–Fri 8:30 AM – 5:00 PM',
    eligibility: 'Low-income Spartanburg County residents. Call ahead to confirm availability.',
    description: 'Free clothing and basic household items for individuals and families in need. Part of Bethlehem Center\'s broader emergency assistance program.',
    website: 'https://www.bethlehemcenter.org',
    mapsUrl: 'https://maps.google.com/?q=1066+W+Main+St+Spartanburg+SC+29301',
  },
];
